on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🔨 Build sites

    runs-on: ubunut-latest
    steps:
      - name: Build static files
        id: build
        run: |
          bun build ./index.html --outdir

      - name: Upload static files as artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    name: 🚀 Deploy sites

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
